apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      role: db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        role: db
    spec:
      containers:
      - name: db
        image: mariadb:10.10
        ports:
        - containerPort: 3306
        resources: {}
status: {}
