
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sandbox

namePrefix: library-

patches:
- path: patches/api-ingress-ssl.yaml
  target:
    kind: Ingress
    name: api-ingress-ssl

resources:
- ../../base/infrastructure

labels:
- includeSelectors: true
  pairs:
    environment: development
    product: library
    stack: infra
