kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2G
