
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    stack: backend

components:
- ../../../components/mariadb

resources:
- db/db-pvc.yaml
- db/db-config.yaml
- api/api-config.yaml
- ../../../base/api


patches:
- path: db/db-deployment.yaml
  target:
    kind: Deployment
    name: db-deploy
- path: api/api-deployment.yaml
  target:
    kind: Deployment
    name: api-deploy

